#!/usr/bin/python

if __name__ == "__main__":
    import argparse
    import logging
    from os.path import expanduser

    from gsmws import controller

    parser = argparse.ArgumentParser(description="GSMWS Controller.")
    parser.add_argument('--openbtsdb', type=str, action='store', default='/etc/OpenBTS/OpenBTS.db', help="OpenBTS.db location")
    parser.add_argument('--openbts', type=str, action='store', default='OpenBTS', help="OpenBTS process name")
    parser.add_argument('--transceiver', type=str, action='store', default='transceiver', help="transceiver process name")
    parser.add_argument('--cycle', '-c', type=int, action='store', default=14400, help="Time before switching to new set of neighbors to scan (seconds).")
    parser.add_argument('--sleep', '-s', type=int, action='store', default=10, help="Time to sleep between RSSI checks (seconds)")
    parser.add_argument('--gsmwsdb', type=str, action='store', default=expanduser("~") + "/gsmws.db", help="Where to store the gsmws.db file")
    parser.add_argument('--cmd', type=str, action='store', default=None, help="Command string to run.")
    parser.add_argument('--stdin', action='store_true', help="Read from STDIN")
    parser.add_argument('--debug', action='store_true', help="Enable debug logging")
    args = parser.parse_args()

    #OPENBTS_DB_LOC="/etc/OpenBTS/OpenBTS.db"
    #OPENBTS_PROCESS_NAME="OpenBTS"
    #TRANSCEIVER_PROCESS_NAME="transceiver"
    #NEIGHBOR_CYCLE_TIME = 4*60*60 # seconds to wait before switching up the neighbor list
    #SLEEP_TIME = 10 # seconds between rssi checks
    #GSMWS_DB = expanduser("~") + "/gsmws.db"

    OPENBTS_DB_LOC=args.openbtsdb
    OPENBTS_PROCESS_NAME=args.openbts
    TRANSCEIVER_PROCESS_NAME=args.transceiver
    NEIGHBOR_CYCLE_TIME = args.cycle # seconds to wait before switching up the neighbor list
    SLEEP_TIME = args.sleep # seconds between rssi checks
    GSMWS_DB = args.gsmwsdb

    if args.debug:
        loglvl = logging.DEBUG
    else:
        loglvl = logging.INFO

    c = controller.Controller(OPENBTS_DB_LOC, OPENBTS_PROCESS_NAME, TRANSCEIVER_PROCESS_NAME, NEIGHBOR_CYCLE_TIME, SLEEP_TIME, GSMWS_DB, loglvl=loglvl)
    if args.stdin:
        c.main(stream=sys.stdin)
    else:
        c.main(cmd=args.cmd)
